#Accounts---------------------------

### Busca todos os cadastros
GET http://localhost:3000/api/accounts


### Cria novo cadastro de conta 
POST http://localhost:3000/api/accounts
Content-Type: application/json

{
  "nome": "Usuario Teste",
  "email": "usuario@example.com",
  "senha": "123456"
}

### Edita um cadastro específico
PUT http://localhost:3000/api/accounts/8a73667e-3f78-4aad-868c-64db34e7f3ad
Content-Type: application/json

{
  "nome": "Victorya",
  "email": "victorya@gmail.com",
  "senha": "novaSenha1234"
}

###Deleta um cadastro específico
DELETE http://localhost:3000/api/accounts/51a5c8ae-384a-401c-8dd0-a82999b175e5
Content-Type: application/json


### Cria novo login 
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "usuario@example.com",
  "senha": "123456"
}


#Aluno---------------------------


### Busca todos os alunos
GET http://localhost:3000/api/aluno

### Cria novo cadastro de aluno 
POST http://localhost:3000/api/aluno
Content-Type: application/json

{
  "objetivo": "Começar uma pósgradução",
  "interesses":"Informatica na educação",
  "bio":"Jovens de 24 anos",
  "lattes_link":"https://lattes.cnpq.br/8070339584568015",
  "id_account": "8540a6b7-e932-4188-804f-aa3d0ba11439"
}


### Edita um aluno específico
PUT http://localhost:3000/api/aluno/da7d37bb-8261-4b3e-bdd3-b69ecee987ad
Content-Type: application/json

{
  "objetivo": "Começar uma iniciação científica",
  "interesses":"Tecnologias inclusivas",
  "bio":"Jovens de 20, estudante do primerio ano do Instituto de Tecnologia e Liderança",
  "lattes_link":"https://lattes.cnpq.br/8070339584568015",
  "id_account": "1e031fcb-e889-441e-8da1-b961761cdf8f"

}

###Deleta um aluno específico
DELETE http://localhost:3000/api/aluno/c2f104e0-4a2d-4a37-ab9c-2c67b22df698
Content-Type: application/json




#Orientador---------------------------


### Busca todos os orientadores
GET http://localhost:3000/api/orientador  


### Cria novo cadastro de orientador 
POST http://localhost:3000/api/orientador
Content-Type: application/json

{
  "expertise": "Ciencia da computação, com foco em machine learning",
  "disponibilidade_data":"2025-06-01",
  "disponibilidade_time":"11:00",
  "bio":"30 anos, Pós graduado em ciência da computação pela USP, com 10 anos de experiência com dados, IA e machine learning",
  "lattes_link": "https://lattes.cnpq.br/8070339584568015",
  "retorno_agendamento": "Aprovado",
  "id_account": "3235b37e-ba38-43b9-bb7a-6445ae9e4972"
}


### Edita um orientador específico
PUT http://localhost:3000/api/orientador/86134783-eb4b-432c-bdcd-1259e77fde76
Content-Type: application/json

{
  "expertise": "Educação e tecnologia",
  "disponibilidade_data":"2025-06-01",
  "disponibilidade_time":"11:00",
  "bio":"30 anos, Pós graduado em informática na educação pela USP, com 5 anos estudando metodologias de ensino",
  "lattes_link": "https://lattes.cnpq.br/8070339584568015",
  "retorno_agendamento": "Aprovado",
  "id_account": "3235b37e-ba38-43b9-bb7a-6445ae9e4972"
}

###Deleta um orientador específico
DELETE http://localhost:3000/api/orientador/f67dcaff-0623-4c88-ae03-deff5ae9aba5
Content-Type: application/json

