#Accounts---------------------------

### Busca todos os cadastros
GET http://localhost:3000/api/accounts


### Cria novo cadastro de conta 
POST http://localhost:3000/api/accounts
Content-Type: application/json


{
  "nome": "Claudio",
  "email": "claudio@email.com",
  "senha": "123456",
  "user_type": "aluno"  
}

### Busca um cadastro específico
GET http://localhost:3000/api/accounts/3235b37e-ba38-43b9-bb7a-6445ae9e4972
Content-Type: application/json


### Edita um cadastro específico
PUT http://localhost:3000/api/accounts/b84dd17c-3bc2-4825-8a10-f1da599302eb
Content-Type: application/json

{
  "nome": "Claudio",
  "email": "claudio@email.com",
  "senha": "123456claudio",
  "user_type": "aluno" 

}

###Deleta um cadastro específico
DELETE http://localhost:3000/api/accounts/b84dd17c-3bc2-4825-8a10-f1da599302eb
Content-Type: application/json


### Acessa novo login 
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "usuario@example.com",
  "senha": "123456"
}


#Aluno---------------------------


### Busca todos os alunos
GET http://localhost:3000/api/aluno

### Cria novo cadastro de aluno 
POST http://localhost:3000/api/aluno
Content-Type: application/json

{
  "objetivo": "Começar uma pósgradução",
  "interesses":"Informatica na educação",
  "bio":"Jovens de 24 anos",
  "lattes_link":"https://lattes.cnpq.br/8070339584568015",
  "id_account": "12e9a42e-c7d3-4561-80be-ee2e4d2e5f13"
}


### Busca um aluno específico
GET http://localhost:3000/api/aluno/da7d37bb-8261-4b3e-bdd3-b69ecee987ad
Content-Type: application/json


### Edita um aluno específico
PUT http://localhost:3000/api/aluno/53a29e99-7c05-4b7f-8893-9ff71e0a4b2b
Content-Type: application/json

{
  "objetivo": "Começar uma iniciação científica",
  "interesses":"Tecnologias inclusivas",
  "bio":"Jovens de 20, estudante do primerio ano do Instituto de Tecnologia e Liderança",
  "lattes_link":"https://lattes.cnpq.br/8070339584568015",
  "id_account": "1e031fcb-e889-441e-8da1-b961761cdf8f"

}

###Deleta um aluno específico
DELETE http://localhost:3000/api/aluno/53a29e99-7c05-4b7f-8893-9ff71e0a4b2b
Content-Type: application/json




#Orientador---------------------------


### Busca todos os orientadores
GET http://localhost:3000/api/orientador  


### Cria novo cadastro de orientador 
POST http://localhost:3000/api/orientador
Content-Type: application/json

{
  "expertise": "Ciencia da computação, com foco em machine learning",
  "disponibilidade_data":"2025-06-01",
  "disponibilidade_time":"11:00",
  "bio":"30 anos, Pós graduado em ciência da computação pela USP, com 10 anos de experiência com dados, IA e machine learning",
  "lattes_link": "https://lattes.cnpq.br/8070339584568015",
  "retorno_agendamento": "True",
  "id_account": "3235b37e-ba38-43b9-bb7a-6445ae9e4972"
}

### Busca um orientadores específico
GET http://localhost:3000/api/orientador/06bacc16-d701-4cd7-99d7-272bcbe1c7c6
Content-Type: application/json

### Edita um orientador específico
PUT http://localhost:3000/api/orientador/
Content-Type: application/json

{
  "expertise": "Educação e tecnologia",
  "disponibilidade_data":"2025-06-01",
  "disponibilidade_time":"11:00",
  "bio":"30 anos, Pós graduado em informática na educação pela USP, com 5 anos estudando metodologias de ensino",
  "lattes_link": "https://lattes.cnpq.br/8070339584568015",
  "retorno_agendamento": "True",
  "id_account": "3235b37e-ba38-43b9-bb7a-6445ae9e4972"
}

###Deleta um orientador específico
DELETE http://localhost:3000/api/orientador/
Content-Type: application/json



#Sessão---------------------------


### Busca todas as sessões
GET http://localhost:3000/api/sessao  


### Cria nova sessão 
POST http://localhost:3000/api/sessao
Content-Type: application/json

{
  "agendamento_data": "2025-06-01",
  "agendamento_hora":"11:00",
  "status":"agendada",
  "external_link":"https://meet.google.com/dkt-bdec-fda",
  "topico": "Revisão de Literatura",
  "id_orientador": "86134783-eb4b-432c-bdcd-1259e77fde76",
  "id_aluno": "da7d37bb-8261-4b3e-bdd3-b69ecee987ad"
}


### Busca uma sessão específica
GET http://localhost:3000/api/sessao/e51c0398-4569-4ce4-9dca-8d6775425da3


### Edita uma sessão específica
PUT http://localhost:3000/api/sessao/e51c0398-4569-4ce4-9dca-8d6775425da3
Content-Type: application/json

{
  "agendamento_data": "2025-06-01",
  "agendamento_hora":"11:00",
  "status":"cancelada",
  "external_link":"https://meet.google.com/dkt-bdec-fda",
  "topico": "Revisão de Literatura",
  "id_orientador": "86134783-eb4b-432c-bdcd-1259e77fde76",
  "id_aluno": "da7d37bb-8261-4b3e-bdd3-b69ecee987ad"
}



###Deleta uma sessão específica
DELETE http://localhost:3000/api/sessao/44e1eb8d-5282-4f83-b10d-39584d6f5721
Content-Type: application/json

